services:
  - type: web
    name: braga-music
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      python manage.py bootstrap_catalogo_demo
    startCommand: gunicorn BragaMusic.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "braga-music.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://braga-music.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: braga-music-db
          property: connectionString
      - key: AUTO_SEED_DEMO
        value: "True"
      - key: MERCADO_PAGO_PUBLIC_KEY
        sync: false
      - key: MERCADO_PAGO_ACCESS_TOKEN
        sync: false

databases:
  - name: braga-music-db
    databaseName: bragamusic
    user: bragamusic_user
