# Generated by Django 5.1.5 on 2025-02-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nome_completo',
            field=models.CharField(default=1, max_length=255, verbose_name='Nome Completo'),
            preserve_default=False,
        ),
    ]
