# Generated by Django 5.1.7 on 2025-03-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0003_cariinho'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cariinho',
            new_name='carrinho',
        ),
    ]
