# Generated by Django 5.1.7 on 2025-03-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0004_rename_cariinho_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_transacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Transação'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='meio_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Meio de Pagamento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20, verbose_name='Status do Pagamento'),
        ),
    ]
