# Generated by Django 5.1.7 on 2025-03-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0005_pedido_codigo_transacao_pedido_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='aceitou_politica',
            field=models.BooleanField(default=False, verbose_name='Aceitou Política de Privacidade'),
        ),
    ]
