# Generated by Django 5.1.7 on 2025-03-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0006_cliente_aceitou_politica'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='bairro_entrega',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro de Entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='bairro_pagador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro do Pagador'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cep_entrega',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP de Entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cep_pagador',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP do Pagador'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cidade_entrega',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade de Entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cidade_pagador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade do Pagador'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='complemento_entrega',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento de Entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='complemento_pagador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento do Pagador'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cpf_pagador',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Pagador'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='email_pagador',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Pagador'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_entrega',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado de Entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_pagador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado do Pagador'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_pagador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Pagador'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_entrega',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de Entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_pagador',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número do Pagador'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='rua_entrega',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rua de Entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='rua_pagador',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rua do Pagador'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sobrenome_pagador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sobrenome do Pagador'),
        ),
    ]
