# Generated by Django 5.1.7 on 2025-04-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0007_pedido_bairro_entrega_pedido_bairro_pagador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageminstrumento',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descrição da Imagem'),
        ),
        migrations.AlterField(
            model_name='imageminstrumento',
            name='imagem',
            field=models.ImageField(upload_to='', verbose_name='Imagem do Instrumento'),
        ),
    ]
