# Generated by Django 5.1.7 on 2025-04-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0008_alter_imageminstrumento_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageminstrumento',
            name='imagem',
        ),
        migrations.AddField(
            model_name='imageminstrumento',
            name='imagem_url',
            field=models.URLField(default=1, max_length=500, verbose_name='URL da Imagem do Instrumento'),
            preserve_default=False,
        ),
    ]
