# Generated by Django 5.1.7 on 2025-04-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0009_remove_imageminstrumento_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageminstrumento',
            name='imagem_url',
        ),
        migrations.AddField(
            model_name='imageminstrumento',
            name='imagem',
            field=models.ImageField(default=1, upload_to='', verbose_name='Imagem do Instrumento'),
            preserve_default=False,
        ),
    ]
